import { desc, eq } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { InsertLeadRecord, InsertUser, leadRecords, users } from "../drizzle/schema";
import { ENV } from "./_core/env";

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch (error) { console.warn("[Database] Failed to connect:", error); _db = null; } } return _db; }
export async function upsertUser(user: InsertUser): Promise<void> { if (!user.openId) throw new Error("User openId is required for upsert"); const db = await getDb(); if (!db) return; const values: InsertUser = { openId: user.openId }; const updateSet: Record<string, unknown> = {}; const textFields = ["name", "email", "loginMethod"] as const; textFields.forEach(field => { if (user[field] !== undefined) { values[field] = user[field] ?? null; updateSet[field] = user[field] ?? null; } }); if (user.lastSignedIn !== undefined) { values.lastSignedIn = user.lastSignedIn; updateSet.lastSignedIn = user.lastSignedIn; } if (user.role !== undefined) { values.role = user.role; updateSet.role = user.role; } else if (user.openId === ENV.ownerOpenId) { values.role = "admin"; updateSet.role = "admin"; } if (!values.lastSignedIn) values.lastSignedIn = new Date(); if (!Object.keys(updateSet).length) updateSet.lastSignedIn = new Date(); await db.insert(users).values(values).onDuplicateKeyUpdate({ set: updateSet }); }
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result.length ? result[0] : undefined; }
export async function insertLeadRecord(record: InsertLeadRecord) { const db = await getDb(); if (!db) return null; await db.insert(leadRecords).values(record); return record; }
export async function listLeadRecordsDb() { const db = await getDb(); if (!db) return []; const rows = await db.select().from(leadRecords).orderBy(desc(leadRecords.createdAt)); return rows.map(row => ({ id: row.recordId, createdAt: row.createdAt.toISOString(), status: row.status, categoria: row.category, clienteNome: row.clientName, empresaNome: row.companyName || undefined, documento: row.document, contato: row.contact, regiao: row.region, cursos: JSON.parse(row.coursesJson || "[]"), destino: row.destination, companyLogoUrl: row.companyLogoUrl || undefined, protocolo: row.protocol, resumo: row.summary || undefined })); }
export async function updateLeadRecordStatus(recordId: string, status: "aberto" | "finalizado") { const db = await getDb(); if (!db) return null; await db.update(leadRecords).set({ status }).where(eq(leadRecords.recordId, recordId)); return { recordId, status }; }
